stages:
  - build

build-images:
  stage: build
  parallel:
    matrix:
      - ARCH: amd64
      - ARCH: arm64
  tags:
    - saas-linux-medium-${ARCH}
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}/build"
      --dockerfile "${CI_PROJECT_DIR}/build/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}-${ARCH}"
  rules:
    - if: '$CI_COMMIT_TAG'

merge-images:
  stage: build
  needs:
    - job: build-images
      artifacts: false
  image:
    name: mplatform/manifest-tool:alpine
    entrypoint: [""]
  script:
    - >-
      manifest-tool
      --username=${CI_REGISTRY_USER} --password=${CI_REGISTRY_PASSWORD} push
      from-args
      --platforms linux/amd64,linux/arm64
      --template ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}-ARCH
      --target ${CI_REGISTRY_IMAGE}:latest
      --target ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
      --target ${CI_REGISTRY_IMAGE}:test
  rules:
    - if: '$CI_COMMIT_TAG'
