stages:
  - build

build-images:
  stage: build
  parallel:
    matrix:
      - ARCH: amd64
      - ARCH: arm64
  tags:
    - saas-linux-medium-${ARCH}
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}/build"
      --dockerfile "${CI_PROJECT_DIR}/build/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${ARCH}"
  only:
    - main
  # rules:
  #   - if: "${CI_COMMIT_TAG}"
