stages:
  - build

build:
  stage: build
  cache:
    - key:
        files:
          - index.html
      paths:
        - delme
  parallel:
    matrix:
      - ARCH: arm64
      - ARCH: amd64
  tags:
    - runner-${ARCH}
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}/build"
      --dockerfile "${CI_PROJECT_DIR}/build/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${ARCH}"
  only:
    - main
