stages:
  - build
  - merge

build-images:
  stage: build
  parallel:
    matrix:
      - ARCH: amd64
      - ARCH: arm64
  tags:
    - saas-linux-medium-${ARCH}
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}/build"
      --dockerfile "${CI_PROJECT_DIR}/build/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${ARCH}"
  only:
    - main
  # rules:
  #   - if: "${CI_COMMIT_TAG}"

# define a job for creating and pushing a merged manifest
merge-images:
  stage: build
  needs:
    - job: build-images
      artifacts: false
  image:
    name: mplatform/manifest-tool:alpine
    entrypoint: [""]
  script:
    - >-
      manifest-tool 
      --username=${CI_REGISTRY_USER} --password=${CI_REGISTRY_PASSWORD} push 
      from-args 
      --platforms amd64,arm64 
      --template ${CI_REGISTRY_IMAGE}:ARCH 
      --target ${CI_REGISTRY_IMAGE}:merged
