stages:
  - build

variables:
  REGISTRY_NAME: docker.io

before_script:
  - echo "{\"auths\":{\"${REGISTRY_URL}\":{\"auth\":\"$(printf "%s:%s" "${REGISTRY_USER}" "${REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json

build-images:
  stage: build
  parallel:
    matrix:
      - ARCH: amd64
      - ARCH: arm64
  tags:
    - saas-linux-medium-${ARCH}
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}/build"
      --dockerfile "${CI_PROJECT_DIR}/build/Dockerfile"
      --destination "${REGISTRY_NAME}/${REGISTRY_PROJECT}:${CI_COMMIT_TAG}-${ARCH}"
  rules:
    - if: '$CI_COMMIT_TAG'

merge-images:
  stage: build
  needs:
    - job: build-images
      artifacts: false
  image:
    name: mplatform/manifest-tool:alpine
    entrypoint: [""]
  script:
    - >-
      manifest-tool
      --username=${REGISTRY_USER} --password=${REGISTRY_PASSWORD} push
      from-args
      --platforms linux/amd64,linux/arm64
      --template ${REGISTRY_NAME}/${REGISTRY_PROJECT}:${CI_COMMIT_TAG}-ARCH
      --target ${REGISTRY_NAME}/${REGISTRY_PROJECT}:latest
      --target ${REGISTRY_NAME}/${REGISTRY_PROJECT}:${CI_COMMIT_TAG}
      --target ${REGISTRY_NAME}/${REGISTRY_PROJECT}:test
  rules:
    - if: '$CI_COMMIT_TAG'
