stages:
  - build

build:
  stage: build
  tags:
    - runner-arm64
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}/build"
      --dockerfile "${CI_PROJECT_DIR}/build/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:arm64"
  only:
    - main
